name: "Project Version Action"
description: "Reusable action for checking the project release version"

inputs:
  project_repo:
    description: "Repository with project code"
    required: true
  
  release_tag:
    description: "Project release number or tag (e.g. v1.0.0)"
    required: true

outputs:
  results_name:
    description: "Name of results artifact"
    value: "${{ steps.check-version.outputs.results_name }}"

  results_json:
    description: "Name of results JSON file"
    value: "${{ steps.check-version.outputs.results_json }}"

runs:
  using: "composite"
  steps:
    - name: 'Checkout Action'
      id: checkout-action
      uses: actions/checkout@v3
      with:
        repository: usf-cs272-fall2022/action-project-version

    - name: 'Check Project Version'
      id: check-version
      uses: actions/github-script@v6
      env:
        PROJECT_REPO: "${{ inputs.project_repo }}"
        RELEASE_TAG:  "${{ inputs.release_tag }}"
      with:
        script: |
          const fs = require('fs');
          const script = require('./index.js');
          const result = await script({github, context, core, fs});
          return result;
  
    - name: 'Upload Results'
      uses: actions/upload-artifact@v3
      id: upload-artifact
      with:
        name: "${{ steps.check-version.outputs.results_name }}"
        path: "${{ steps.check-version.outputs.results_json }}"
